# Generated by Django 5.0.4 on 2025-11-15 12:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeScreeningTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("current_step", models.IntegerField(default=1)),
                ("total_steps", models.IntegerField(default=1)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("resume_data", models.JSONField()),
                ("position_data", models.JSONField()),
            ],
            options={
                "db_table": "resume_screening_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("md_file", models.FileField(upload_to="screening_reports/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="resume_screening.resumescreeningtask",
                    ),
                ),
            ],
            options={
                "db_table": "screening_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
