# Generated by Django 5.0.4 on 2025-11-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumescreeningtask",
            name="celery_task_id",
        ),
        migrations.RemoveField(
            model_name="resumescreeningtask",
            name="position_data",
        ),
        migrations.RemoveField(
            model_name="resumescreeningtask",
            name="resume_data",
        ),
        migrations.AlterField(
            model_name="resumescreeningtask",
            name="current_step",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="screeningreport",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="resume_screening.resumescreeningtask",
            ),
        ),
    ]
