# Generated by Django 5.0.4 on 2025-11-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0002_remove_resumescreeningtask_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumescreeningtask",
            name="current_speaker",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
