# Generated by Django 5.0.4 on 2025-11-17 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0003_resumescreeningtask_current_speaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumescreeningtask",
            name="position_data",
            field=models.JSONField(blank=True, null=True, verbose_name="岗位信息"),
        ),
        migrations.AddField(
            model_name="screeningreport",
            name="resume_content",
            field=models.TextField(blank=True, null=True, verbose_name="简历内容"),
        ),
        migrations.CreateModel(
            name="ResumeData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "position_title",
                    models.CharField(max_length=255, verbose_name="岗位名称"),
                ),
                ("position_details", models.JSONField(verbose_name="岗位详细信息")),
                (
                    "candidate_name",
                    models.CharField(max_length=100, verbose_name="候选人姓名"),
                ),
                ("resume_content", models.TextField(verbose_name="简历内容")),
                (
                    "screening_score",
                    models.JSONField(blank=True, null=True, verbose_name="筛选评分"),
                ),
                (
                    "screening_summary",
                    models.TextField(blank=True, null=True, verbose_name="筛选总结"),
                ),
                (
                    "resume_file_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="简历文件哈希值"
                    ),
                ),
                (
                    "report_md_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="screening_reports/%Y/%m/%d/",
                        verbose_name="报告MD文件",
                    ),
                ),
                (
                    "report_json_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="screening_reports/%Y/%m/%d/",
                        verbose_name="报告JSON文件",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_data",
                        to="resume_screening.screeningreport",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_data",
                        to="resume_screening.resumescreeningtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "简历数据",
                "verbose_name_plural": "简历数据",
                "db_table": "resume_data",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate_name"], name="resume_data_candida_545fc8_idx"
                    ),
                    models.Index(
                        fields=["position_title"], name="resume_data_positio_111d8a_idx"
                    ),
                    models.Index(
                        fields=["resume_file_hash"],
                        name="resume_data_resume__9b8c34_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="resume_data_created_acbfa8_idx"
                    ),
                ],
            },
        ),
    ]
