# Generated by Django 5.0.4 on 2025-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0004_resumescreeningtask_position_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedata",
            name="json_report_content",
            field=models.TextField(blank=True, null=True, verbose_name="JSON报告内容"),
        ),
        migrations.AddField(
            model_name="screeningreport",
            name="json_report_content",
            field=models.TextField(blank=True, null=True, verbose_name="JSON报告内容"),
        ),
    ]
