# Generated by Django 5.0.4 on 2025-11-18 00:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0005_resumedata_json_report_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "position_title",
                    models.CharField(max_length=255, verbose_name="岗位名称"),
                ),
                ("position_details", models.JSONField(verbose_name="岗位详细信息")),
                (
                    "position_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="岗位信息哈希值"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=255, verbose_name="简历组名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="组描述"),
                ),
                (
                    "resume_count",
                    models.IntegerField(default=0, verbose_name="简历数量"),
                ),
            ],
            options={
                "verbose_name": "简历组",
                "verbose_name_plural": "简历组",
                "db_table": "resume_groups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["position_title"], name="resume_grou_positio_5219f5_idx"
                    ),
                    models.Index(
                        fields=["position_hash"], name="resume_grou_positio_55d53f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="resume_grou_created_950ece_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="resumedata",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumes",
                to="resume_screening.resumegroup",
            ),
        ),
    ]
