# Generated by Django 5.0.4 on 2025-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0006_resumegroup_resumedata_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumegroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待分析"),
                    ("interview_analysis", "面试分析中"),
                    ("comprehensive_screening", "综合筛选中"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=30,
                verbose_name="状态",
            ),
        ),
        migrations.AddIndex(
            model_name="resumegroup",
            index=models.Index(fields=["status"], name="resume_grou_status_120ff3_idx"),
        ),
    ]
