# Generated by Django 5.0.4 on 2025-11-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0007_resumegroup_status_and_more"),
        ("video_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumedata",
            name="video_analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_resume_data",
                to="video_analysis.videoanalysis",
            ),
        ),
    ]
