# Generated by Django 5.0.4 on 2025-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0008_resumedata_video_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumegroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待分析"),
                    ("interview_analysis", "面试分析中"),
                    ("interview_analysis_completed", "面试分析已完成"),
                    ("comprehensive_screening", "综合筛选中"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=30,
                verbose_name="状态",
            ),
        ),
    ]
