# Generated by Django 5.0.4 on 2025-11-20 04:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewEvaluationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("group_id", models.CharField(max_length=255, verbose_name="简历组ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="处理进度")),
                (
                    "current_speaker",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="当前发言者"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="interview_evaluation_reports/%Y/%m/%d/",
                        verbose_name="评估报告文件",
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="评估结果摘要"
                    ),
                ),
            ],
            options={
                "verbose_name": "面试评估任务",
                "verbose_name_plural": "面试评估任务",
                "db_table": "interview_evaluation_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
