# Generated by Django 5.0.4 on 2025-11-19 08:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "video_name",
                    models.CharField(max_length=255, verbose_name="视频名称"),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="video_analysis/videos/%Y/%m/%d/",
                        verbose_name="视频文件",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(max_length=100, verbose_name="候选人姓名"),
                ),
                (
                    "position_applied",
                    models.CharField(max_length=255, verbose_name="应聘岗位"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "分析中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="分析状态",
                    ),
                ),
                (
                    "fraud_score",
                    models.FloatField(blank=True, null=True, verbose_name="欺诈评分"),
                ),
                (
                    "neuroticism_score",
                    models.FloatField(blank=True, null=True, verbose_name="神经质评分"),
                ),
                (
                    "extraversion_score",
                    models.FloatField(blank=True, null=True, verbose_name="外倾性评分"),
                ),
                (
                    "openness_score",
                    models.FloatField(blank=True, null=True, verbose_name="开放性评分"),
                ),
                (
                    "agreeableness_score",
                    models.FloatField(blank=True, null=True, verbose_name="宜人性评分"),
                ),
                (
                    "conscientiousness_score",
                    models.FloatField(blank=True, null=True, verbose_name="尽责性评分"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="分析摘要"),
                ),
                (
                    "confidence_score",
                    models.FloatField(blank=True, null=True, verbose_name="置信度评分"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "视频分析",
                "verbose_name_plural": "视频分析",
                "db_table": "video_analysis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate_name"], name="video_analy_candida_78f58f_idx"
                    ),
                    models.Index(
                        fields=["position_applied"],
                        name="video_analy_positio_5a3971_idx",
                    ),
                    models.Index(
                        fields=["status"], name="video_analy_status_879c85_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="video_analy_created_d8ed00_idx"
                    ),
                ],
            },
        ),
    ]
